stages:
  - maven-compile
  - maven-test
  - maven-verify
  
## The maven variables can be set globally because they are used in every single job
variables:
  ADDITIONAL_MAVEN_OPTS: "-Dtest.bla=true"
  PARENT_POM_LOCATION: "releng/"

include:
  - project: 'BestSolution.at/gitlab-pipelines'
    ref: 1.4.3
    file: 
      - '/templates/maven-base.yml'
      - '/jobs/maven/compile.yml'
      - '/jobs/maven/verify.yml'

master-test:
  stage: maven-test
  script:
    - echo "<--- testing --->"
    - mvn clean test
  artifacts:
    expire_in: 10 mins
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        



