stages:
  - maven-compile
  - maven-verify
  - maven-sonar
  - docker-prepare
  - docker-build
  - docker-deploy
  
include:
  - project: 'BestSolution.at/gitlab-pipelines'
    ref: 1.11.0
    file: 
      - '/templates/maven-base.yml'
      - '/jobs/maven/compile.yml'
      - '/jobs/maven/verify.yml'
      - '/jobs/maven/sonar.yml'
      - '/jobs/docker/build.yml'

maven-verify:
  artifacts:
    reports:
      junit:
        - ./**/target/surefire-reports/TEST-*Test.xml

collect-metadata:
  extends: .maven
  stage: docker-prepare
  script:
    - echo "QUAK_BUILD_TIME=$(date --date="${CI_PIPELINE_CREATED_AT}" --utc +%Y-%m-%dT%H:%M:%SZ)" >> buildinfo.env
    - cd $CI_PARENT_POM_LOCATION
    - mvn $CI_MAVEN_OPTS $ADDITIONAL_MAVEN_OPTS org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression="project.version" -Doutput=maven-project-version.txt
    - echo "QUAK_VERSION=$(cat maven-project-version.txt)" >> ${CI_PROJECT_DIR}/buildinfo.env
  rules:
    - !reference [docker-build, rules]
  needs: []
  cache:
    paths:
      - ".m2/repository/"
    key: $CI_COMMIT_REF_SLUG
    policy: pull
  artifacts:
    expire_in: 6 hours
    reports:
      dotenv: buildinfo.env

docker-build:
  variables:
    IMAGE_NAME: "quak"
    DOCKER_BUILD_ARGUMENTS: >-
      --label org.opencontainers.image.created=${QUAK_BUILD_TIME}
      --label org.opencontainers.image.revision=${CI_COMMIT_SHA}
      --label org.opencontainers.image.version=${QUAK_VERSION}
      
docker-hub-deploy:
  stage: docker-deploy
  image: nexus.ci.bestsolution.at:8083/docker:stable
  variables:
    DOCKERHUB_IMAGE_BASE: "docker.io/bestsolutionat/quak"
  before_script:
    - |
      export CI_APPLICATION_REPOSITORY=${CI_REGISTRY_IMAGE}/${IMAGE_NAME}
      export IMAGE_TAGGED=${CI_APPLICATION_REPOSITORY}:${CI_COMMIT_SHA}
    - |
      echo "Logging in to GitLab Container Registry with CI credentials..."
      echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - |
      echo "Logging in to Docker Hub with credentials..."
      echo "$DOCKER_HUB_TOKEN" | docker login -u "$DOCKER_HUB_USER" --password-stdin"
  script:
    - docker pull ${IMAGE_LATEST}
    - docker tag ${IMAGE_LATEST} ${DOCKERHUB_IMAGE_BASE}:${QUAK_VERSION}
    - docker push ${DOCKERHUB_IMAGE_BASE}:${QUAK_VERSION}
    - docker tag ${IMAGE_LATEST} ${DOCKERHUB_IMAGE_BASE}:latest
    - docker push ${DOCKERHUB_IMAGE_BASE}:latest
  rules:
    - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH && $CI_COMMIT_TAG =~ /^R.*/'
      when: manual
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_TAG =~ /^R.*/ && $CI_DEPLOY_FREEZE != null'
      when: manual
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_TAG =~ /^R.*/'
      when: on_success
