stages:
  - maven-compile
  - maven-verify
  
include:
  - project: 'BestSolution.at/gitlab-pipelines'
    ref: 1.4.3
    file: 
      - '/templates/maven-base.yml'
      - '/jobs/maven/compile.yml'
      - '/jobs/maven/verify.yml'
        



