stages:
  - maven-compile
  - maven-verify
  - maven-sonar
  - docker-prepare
  - docker-build
  
include:
  - project: 'BestSolution.at/gitlab-pipelines'
    ref: 1.11.0
    file: 
      - '/templates/maven-base.yml'
      - '/jobs/maven/compile.yml'
      - '/jobs/maven/verify.yml'
      - '/jobs/maven/sonar.yml'
      - '/jobs/docker/build.yml'

maven-verify:
  artifacts:
    reports:
      junit:
        - ./**/target/surefire-reports/TEST-*Test.xml

collect-metadata:
  extends: .maven
  stage: docker-prepare
  variables:
    GIT_STRATEGY: none
    CI_MAVEN_OPTS: "--fail-at-end"
  script:
    - rm -f buildinfo.env
    - echo "QUAK_BUILD_TIME=$(date --date="${CI_PIPELINE_CREATED_AT}" --rfc-3339=seconds)" >> buildinfo.env
    - cd $CI_PARENT_POM_LOCATION
    - echo "QUAK_VERSION=$(mvn $CI_MAVEN_OPTS $ADDITIONAL_MAVEN_OPTS help:evaluate -Dexpression=project.version -q -DforceStdout)" >> ${CI_PROJECT_DIR}/buildinfo.env
  rules:
    - !reference [docker-build, rules]
  needs: []
  artifacts:
    expire_in: 6 hours
    reports:
      dotenv: buildinfo.env

docker-build:
  variables:
    IMAGE_NAME: "quak"
    DOCKER_BUILD_ARGUMENTS: >-
      --label org.opencontainers.image.created="${QUAK_BUILD_TIME}"
      --label org.opencontainers.image.revision="${CI_COMMIT_SHA}"
      --label org.opencontainers.image.version="${QUAK_VERSION}"
