image: registry.bestsolution.dev/bestsolution.at/docker-images/docker-zulufx-mvn/beso-zulufx11-mvn:latest

stages:
  - compile
  - test
  - build
  - verify
  
master-compile:
  stage: compile
  script:
    - echo "<--- compiling --->"
    - mvn clean compile
  artifacts:
    expire_in: 10 mins

master-test:
  stage: test
  script:
    - echo "<--- testing --->"
    - mvn clean test
  artifacts:
    expire_in: 10 mins
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        
master-verify:
  stage: verify
  script:
    - mvn sonar:sonar   -Dsonar.host.url=https://$SONAR_HOST    -Dsonar.login=$SONAR_LOGIN
  artifacts:
    expire_in: 10 mins
    paths: ['target/']

master-build:
  stage: build
  script:
    - echo "<-- building --->"
    - mvn clean package
  artifacts:
    expire_in: 10 mins
    paths:
      # create an artifact for the build jar
      - target/quak-1.0.0-SNAPSHOT.jar



