stages:
  - maven-compile
  - maven-verify
  - maven-sonar
  - docker-build
  
include:
  - project: 'BestSolution.at/gitlab-pipelines'
    ref: 1.11.0
    file: 
      - '/templates/maven-base.yml'
      - '/jobs/maven/compile.yml'
      - '/jobs/maven/verify.yml'
      - '/jobs/maven/sonar.yml'
      - '/jobs/docker/build.yml'

maven-verify:
  artifacts:
    reports:
      junit:
        - ./**/target/surefire-reports/TEST-*Test.xml
        
docker-build:
  variables:
    IMAGE_NAME: "quak"
    DOCKER_EXTRA_TAG: "quak"

        
        