stages:
  - maven-compile
  - maven-verify
  - maven-sonar
  
include:
  - project: 'BestSolution.at/gitlab-pipelines'
    ref: 1.11.0
    file: 
      - '/templates/maven-base.yml'
      - '/jobs/maven/compile.yml'
      - '/jobs/maven/verify.yml'
      - '/jobs/maven/sonar.yml'

maven-verify:
  artifacts:
    reports:
      junit:
        - ./*/target/surefire-reports/TEST-*.xml
